version: "3.8"

# docker run -it --rm --name frontend -v ".:/app" -w "/app" -p 3000:3000 node:20.9.0-alpine3.18 sh

# docker compose build
# docker compose up
# docker compose down
# docker compose logs frontend
# docker compose exec -it frontend sh

services:
  frontend:
    restart: always
    build: .
    image: frontend:v1
    container_name: frontend
    # command: npm install && npm run dev
    ports:
      - 8080:8080
    networks:
      - app

networks:
  app:
